server:
  port: 8081

spring:
  application:
    name: habitaciones-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000 # Dónde está el Authorization Server

security:
  exposed-ant-matchers: